networks:
  ayon:
    name: network_ayon-10-2
  dagster:
    name: network_dagster
  mongodb:
    name: network_mongodb-10-2
  repository:
    name: network_repository-10-2
services:
  dagster:
    command:
    - dagster
    - dev
    - --workspace
    - /dagster/workspace.yaml
    - --host
    - 0.0.0.0
    - --port
    - '3006'
    container_name: dagster--2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    depends_on:
    - openstudiolandscapes-postgres-dagster
    domainname: farm.evil
    environment:
      DAGSTER_DEPLOYMENT: farm
      DAGSTER_HOME: /dagster/materializations
      DAGSTER_JOBS_IN: /data/share/nfs/in
    healthcheck:
      interval: 10s
      retries: '3'
      test:
      - CMD
      - curl
      - -f
      - http://localhost:3006
      timeout: 2s
    hostname: dagster.farm.evil
    image: docker.io/openstudiolandscapes_dagster_build_docker_image:2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    networks:
    - mongodb
    - repository
    - ayon
    - dagster
    ports:
    - 3003:3006
    restart: always
    volumes:
    - /data/share/nfs:/data/share/nfs
    - /data/share/nfs:/nfs
    - 2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9/Dagster__Dagster/Dagster__dagster_yaml/materializations:/dagster/materializations:rw
    - 2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9/Dagster__Dagster/Dagster__workspace_yaml/workspace.yaml:/dagster/workspace.yaml:ro
  openstudiolandscapes-postgres-dagster:
    container_name: openstudiolandscapes-postgres-dagster--2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    domainname: farm.evil
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    healthcheck:
      interval: 10s
      retries: '5'
      test:
      - CMD-SHELL
      - pg_isready --username postgres --dbname postgres --port 5432
      timeout: 8s
    hostname: openstudiolandscapes-postgres-dagster.farm.evil
    image: docker.io/postgres
    networks:
    - mongodb
    - repository
    - ayon
    - dagster
    restart: always
    volumes:
    - .dagster/postgres:/var/lib/postgresql/data/pgdata
