networks:
  kitsu:
    name: network_kitsu
services:
  kitsu:
    command:
    - bash
    - /opt/zou/start_zou.sh
    container_name: kitsu--2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    depends_on:
      kitsu-init-db:
        condition: service_completed_successfully
    domainname: farm.evil
    environment:
      DB_PASSWORD: mysecretpassword
      ENABLE_JOB_QUEUE: true
      KITSU_ADMIN: admin@example.com
      PREVIEW_FOLDER: /opt/zou/previews
      SECRET_KEY: yourrandomsecretkey
      TMP_DIR: /opt/zou/tmp
    hostname: kitsu.farm.evil
    image: docker.io/openstudiolandscapes_kitsu_build_docker_image:2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    networks:
    - kitsu
    ports:
    - 4545:80
    restart: always
    volumes:
    - 2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9/Kitsu__Kitsu/data/kitsu/postgresql:/var/lib/postgresql
    - 2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9/Kitsu__Kitsu/data/kitsu/previews:/opt/zou/previews
    - /data/share/nfs:/data/share/nfs
    - /data/share/nfs:/nfs
    - 2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9/Kitsu__Kitsu/Kitsu__supervisord_conf/supervisord.conf:/etc/supervisord.conf:ro
  kitsu-init-db:
    command:
    - /usr/bin/bash
    - /opt/zou/init_db.sh
    container_name: kitsu-init-db--2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    domainname: farm.evil
    environment:
      DB_PASSWORD: mysecretpassword
      KITSU_ADMIN: admin@example.com
      PREVIEW_FOLDER: /opt/zou/previews
      SECRET_KEY: yourrandomsecretkey
      TMP_DIR: /opt/zou/tmp
    hostname: kitsu-init-db.farm.evil
    image: docker.io/openstudiolandscapes_kitsu_build_docker_image:2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    restart: 'no'
    volumes:
    - 2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9/Kitsu__Kitsu/data/kitsu/postgresql:/var/lib/postgresql
    - /data/share/nfs:/data/share/nfs
    - /data/share/nfs:/nfs
