networks:
  ayon:
    name: network_ayon-10-2
services:
  postgres:
    container_name: ayon-postgres--2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    domainname: farm.evil
    hostname: postgres.farm.evil
    networks:
    - ayon
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/user/git/repos/OpenStudioLandscapes/.landscapes/2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9/Ayon__Ayon/data/ayon-db/postgresql:/var/lib/postgresql/data:rw
  redis:
    container_name: ayon-redis--2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    domainname: farm.evil
    hostname: redis.farm.evil
    networks:
    - ayon
  server:
    container_name: ayon-server--2025-07-09-10-57-24-9749b6a35f504cce82b6622608cf10a9
    domainname: farm.evil
    hostname: server.farm.evil
    networks:
    - ayon
    ports: !override
    - 5005:5000
