networks:
  ayon:
    name: network_ayon-10-2
services:
  postgres:
    container_name: ayon-postgres--2025-07-10-22-36-50-47cd6c0a7dd141429707ab6d91190a27
    domainname: farm.evil
    hostname: postgres.farm.evil
    networks:
    - ayon
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/user/git/repos/OpenStudioLandscapes/.landscapes/2025-07-10-22-36-50-47cd6c0a7dd141429707ab6d91190a27/Ayon__Ayon/data/ayon-db/postgresql:/var/lib/postgresql/data:rw
  redis:
    container_name: ayon-redis--2025-07-10-22-36-50-47cd6c0a7dd141429707ab6d91190a27
    domainname: farm.evil
    hostname: redis.farm.evil
    networks:
    - ayon
  server:
    container_name: ayon-server--2025-07-10-22-36-50-47cd6c0a7dd141429707ab6d91190a27
    domainname: farm.evil
    hostname: server.farm.evil
    networks:
    - ayon
    ports: !override
    - 5005:5000
